% -------------------------------------------------------------------
%  Generated by MATLAB on 26-Oct-2016 10:32:53
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('DetectColor.mat');

NAME = 'Mirage';

angle = single(-885);

ans = single(NaN);

brick = saveVarsMat.brick; % <1x1 Brick> unsupported class

currTurn = 5;

dank = [1 2 3];

dist = single(255);

turns = 'LLRLLR';

clear saveVarsMat;
